name: 'Kubernetes Deploy'
description: 'Deploy to Kubernetes cluster'
inputs:
  kubeconfig:
    description: 'Kubernetes config'
    required: true
  manifest-path:
    description: 'Path to Kubernetes manifest'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.kubeconfig }}
        
    - name: Update image tag in manifests
      shell: bash
      run: |
        sed -i 's|${{ inputs.image-name }}:v[0-9]*|${{ inputs.image-name }}:${{ inputs.image-tag }}|g' ${{ inputs.manifest-path }}
        
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v5
      with:
        manifests: ${{ inputs.manifest-path }}