name: 'Docker Build and Push'
description: 'Build and push Docker image'
inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-token:
    description: 'Docker Hub token'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: true
  context-path:
    description: 'Build context path'
    required: true
  tag:
    description: 'Image tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ inputs.image-name }}:${{ inputs.tag }}
        file: ${{ inputs.dockerfile-path }}
        context: ${{ inputs.context-path }}